Builder: Support other parts
jhillyerd/enmime pull request #244
Opened 2022-04-14 09:33 UTC by lcd1232

Closes #223
I moved other parts in multipart/related as inlines because I saw [this image](https://stackoverflow.com/a/66551704/5996922)
Tested on eml message, looks fine

2022-04-15 04:00 UTC, jhillyerd commented
I actually removed testify from the codebase back in 2016, would rather not re-introduce it, not a fan.  https://github.com/jhillyerd/enmime/commit/8f740ea94617eb982c13213ab4ca41ff05186a84

2022-04-15 05:50 UTC, iredmail commented
I like testify since it saves a lot typing. :)

2022-04-15 15:16 UTC, jhillyerd commented
It was a while ago, so I forget the exact reasons, but my primary problem was that it's test output was not parseable when running the tests from vim, the colors looked like crap and jumping to the point of failure didn't work.   I also didn't like importing unnecessary things that could cause conflicts as a library to be used by others, I think go mod is smart enough to not force test dependencies on our users so probably less of a problem nowdays.

2022-04-16 12:25 UTC, lcd1232 commented
@jhillyerd do you think I should remove testify?

2022-04-16 18:39 UTC, jhillyerd commented
I tried this morning, testify no longer breaks go-vim, and doesn't seem any worse than any other failed tests with multi-line output.

If I read https://go.dev/ref/mod#graph-pruning correctly, our choices will still impact the modules that import us until everyone is on Go 1.18.

With that in mind, let's keep testify, but switch from 1.7.1 (very new, and not properly released on github), to 1.7.0 which has been around for more than a year.  That way folks that import us have more control over when they move to 1.7.1.

2022-04-16 18:54 UTC, jhillyerd requested changes

2022-04-16 18:54 UTC, jhillyerd commented on go.mod
> +	github.com/stretchr/testify v1.7.1 // indirect
Switch to 1.7.0

2022-04-19 18:30 UTC, lcd1232 commented on go.mod
> +	github.com/stretchr/testify v1.7.1 // indirect
Done

2022-04-20 02:26 UTC, jhillyerd commented on go.mod
> +	github.com/stretchr/testify v1.7.1 // indirect
Thanks!

2022-04-20 02:26 UTC, merged