fix: buffer overrun when quoted printable is at the end of line and output buffer
jhillyerd/enmime pull request #254
Opened 2022-06-02 09:21 UTC by pavelbazika

In QPCleaner, write behind the buffer end could occur, when there was a `=XX` quoted printable token, line length was 1023 and remaining dest buffer space was only 1 byte. Because of line length, QPCleaner inserted `=\r\n`, but only the equal sign fit into the output buffer. The rest went to qp.overflow. 

Then the algorithm wrote to `dest[n]` without any additional checks, but `n` already pointed behind the buffer end.

Now the equal sign is also written to overflow in such situation.

I've also noticed, that qp.lineLength is not incremented when qp.overflow is put at the beginning of new buffer and also when `=` from quoted printable token is inserted. Seems as a bug to me, but I don't fix it in this PR.

2022-06-02 15:42 UTC, jhillyerd commented on internal/coding/quotedprint_test.go
> +		t.Errorf("Unexpected result length: %d", n)
Can we add std Go "got: %v, wanted: %v" syntax to all four of these failures, they will be easily confused.

2022-06-02 15:42 UTC, jhillyerd requested changes
Thanks, one small change requested.  Should I file a bug for the other issue you mentioned?

2022-06-05 17:40 UTC, pavelbazika commented on internal/coding/quotedprint_test.go
> +		t.Errorf("Unexpected result length: %d", n)
Ok, done. I did not know about such std, personally I use `require` package.

2022-06-05 17:43 UTC, pavelbazika commented
> Thanks, one small change requested. Should I file a bug for the other issue you mentioned?

No need to file a bug, I'll fix it and come with a PR. I just wanted to ensure, that `lineLength` should be incremented in all circumstances.

2022-06-05 18:37 UTC, jhillyerd commented on internal/coding/quotedprint_test.go
> +		t.Errorf("Unexpected result length: %d", n)
Thanks!

Not super important, but if you look through the go std lib, you will see this pattern over and over:

	if got, want := a.Get(&v1), 1; got != want {
		panic(fmt.Sprintf("Get() == %d, want %d", got, want))
	}

Basically they almost always use `got` and `want`, and got is placed before want in both the equality test and the failure output text.

We did introduce stretchr/testify back into enmime recently.  I wouldn't want to add `require` as well, but feel free to use testify assertions if you prefer those to vanilla go.

2022-06-05 18:40 UTC, jhillyerd approved these changes

2022-06-05 18:41 UTC, merged

2022-07-21 00:47 UTC, jhillyerd commented
Just tagged 0.10.0