feat: add field accessors for mailbuilder
jhillyerd/enmime pull request #261
Opened 2022-08-17 03:13 UTC by andylibrian

Hi, this PR is to implement the field accessors for `MailBuilder` as proposed in #260

2022-08-17 15:38 UTC, jhillyerd commented
I need to take a deeper look, but my initial concern with the values being returned is that they may allow the original value to be mutated -- which goes against the expectations of a Go builder.  I think we'll probably need to do some copying or deep copying on the returned values.

2022-08-21 04:07 UTC, andylibrian commented
Hi @jhillyerd, thanks for letting me know your concern. I'm ok with returning the copied values. Once you are sure this is the way to go, please let me know, I'll update the PR to use returned values instead.

2022-08-22 23:50 UTC, jhillyerd requested changes
Thanks, looks like we only need to worry about mutability with the slice types.

2022-08-22 23:50 UTC, jhillyerd commented on builder.go
> +	return p.to
Let's use the following style to return a copy of the to slice:

var dst []string
dst = append(dst, src...)

2022-08-22 23:50 UTC, jhillyerd commented on builder.go
> +	return p.cc
ditto for this one

2022-08-22 23:50 UTC, jhillyerd commented on builder.go
> +	return p.bcc
and this one

2022-08-22 23:50 UTC, jhillyerd commented on builder.go
> +	return p.text
this will also need to be copied.

2022-08-22 23:50 UTC, jhillyerd commented on builder.go
> +	return p.html
and this one.

2022-08-24 01:10 UTC, jhillyerd approved these changes

2022-08-24 01:11 UTC, merged

2022-08-24 01:11 UTC, jhillyerd commented
Thanks!