feat: add parser option to parse raw content
jhillyerd/enmime pull request #304
Opened 2023-10-09 16:34 UTC by jerjako

Add an option to the parser to skip the auto-detect of the CTE. And return the content unchanged

2023-10-11 16:54 UTC, jhillyerd commented
I'm in favor of this, but have two concerns:

1. I don't like that a "Parser" option is changing the output of the encoder.  Given we don't have a way to set encoding options, I think we can live with this for now.
2. This change must add unit tests, otherwise it will be too easy to break in the future.

2023-10-13 09:19 UTC, jerjako commented
Thank you @jhillyerd
I know what you mean, I'm not a fan either. I've tested to change the behavior of the Encode function, but without luck.
I've added a simple test that will show the diff with and without the option.

2023-10-16 19:25 UTC, jhillyerd requested changes
Looks good, just a couple small changes, thanks.

2023-10-16 19:25 UTC, jhillyerd commented on testdata/encode/parser-raw-content-option-false.raw
Let's use the `.golden` extension instead of `.raw` to be consistent with the other golden tests in the project.

2023-10-16 19:25 UTC, jhillyerd commented on testdata/encode/parser-raw-content-option-true.raw
Let's use the `.golden` extension instead of `.raw` to be consistent with the other golden tests in the project.

2023-10-16 19:25 UTC, jhillyerd commented on testdata/encode/parser-raw-content-option.raw
This can keep `.raw` as it's an input.

2023-10-17 07:12 UTC, jerjako commented on testdata/encode/parser-raw-content-option.raw
Ok, done 👍

2023-10-17 07:13 UTC, jerjako commented on testdata/encode/parser-raw-content-option-false.raw
Oh yes, I miss that, thank you.

2023-10-17 21:43 UTC, merged

2023-10-17 21:43 UTC, jhillyerd commented
Thanks!