feat: encoding options added
jhillyerd/enmime pull request #359
Opened 2024-12-13 13:05 UTC by pgradoboev

James, please look at the proposed changes.

2024-12-14 19:52 UTC, jhillyerd requested changes
I like adding the Encoder options.

I don't accept PRs without tests, as subsequent PRs to the same code often end up breaking or reverting that feature.  Take a look at this test as a possible starting point:
https://github.com/jhillyerd/enmime/blob/1d9fc9cfdfa5080fc6c0235c57166fab72c56671/encode_test.go#L327

2024-12-14 19:52 UTC, jhillyerd commented on encoder_options.go
> +	enforceQuotedCte bool
In my opinion, `enforce` is the wrong term, as quoted-cte is not a rule or policy.  Just use `force` here and elsewhere.

2024-12-14 19:52 UTC, jhillyerd commented on encoder_options.go
> +// EnforceQuotedPrintableCte enforces "quoted-printable" transfer encoding when selecting Content Transfer Encoding.
```suggestion
// EnforceQuotedPrintableCte forces "quoted-printable" transfer encoding when selecting Content Transfer Encoding, preventing the use of base64.
```

2024-12-14 19:52 UTC, jhillyerd commented on encode.go
>  	if len(content) == 0 {
```suggestion
	if len(content) == 0 || p.encoder != nil && p.encoder.enforceQuotedCte {
```
I think most of the changes you made to this func are not needed, we don't care about a threshold if we are always selecting te7Bit?

2025-01-05 19:36 UTC, jhillyerd commented
Looks pretty good to me, not sure if you're ready for review since it's still marked as draft?

2025-01-06 18:04 UTC, pgradoboev commented
James, I wanted to add more tests after the holidays. But if you think that's enough, then I've changed the request status.

2025-01-12 22:05 UTC, jhillyerd approved these changes
Made a tweak to the test to check a bit of the encoded content.

2025-01-12 22:06 UTC, merged